# Command to read the pulse duration measured by one of the sensor adapters.

uint8 id       # 0 or 1: ID of one of two interfaces of a sensor adapter
uint8 port     # 0, 1, 2, or 3: ID of one of the 4 sensor adapter that can be connected to the robot
---
bool valid     # whenever the sensor adapter is enabled
uint32 time_ms # the pulse duration in milliseconds
