FROM ros:rolling
MAINTAINER Jerome Guzzi "jerome@idsia.ch"

RUN apt-get update && apt-get install -y --no-install-recommends \
    locales \
    python3-pip \
    python3-numpy \
    python3-scipy \
    ros-rolling-xacro \
    ros-rolling-cv-bridge \
    ros-rolling-joint-state-publisher \
    ros-rolling-joy \
    ros-rolling-joy-teleop \
    ros-rolling-joy-linux \
    ros-rolling-urdfdom \
    ros-rolling-ffmpeg_image_transport_msgs \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8

SHELL ["/bin/bash", "-c"]

RUN python3 -m pip install -U numpy numpy-quaternion PyYaml av
RUN python3 -m pip install git+https://github.com/jeguzzi/RoboMaster-SDK.git
RUN python3 -m pip install -i https://test.pypi.org/simple/ rm-libmedia-codec

COPY ./robomaster_msgs /ros_ws/src/robomaster_msgs
COPY ./robomaster_description /ros_ws/src/robomaster_description
COPY ./robomaster_ros /ros_ws/src/robomaster_ros

RUN cd /ros_ws \
    && source /ros_entrypoint.sh \
    && colcon build --install-base /opt/ros/ws --merge-install \
    && rm -r /ros_ws

RUN /bin/sed -i \
  '/source "\/opt\/ros\/$ROS_DISTRO\/setup.bash"/a source "\/opt\/ros\/ws\/setup.bash"' \
  /ros_entrypoint.sh