# The gripper goal to open, close, or pause, by applying some power.
#
# The action succeeds when the gripper reaches the the target state.

uint8 PAUSE=0                        # the gripper state when manually stopped
uint8 OPEN=1                         # the open gripper state
uint8 CLOSE=2                        # the closed gripper state

uint8 target_state                   # the target gripper state:
                                     # one of ``PAUSE``, ``OPEN``, or ``CLOSE``
float32 power 0.5                    # the relative amount of power in [0, 1]
---

builtin_interfaces/Duration duration # the duration of the action

---

uint8 current_state                  # the current gripper state:
                                     # one of ``PAUSE``, ``OPEN``, or ``CLOSE``
