# An action to rotate a servo using the onboard control.
#
# The action succeeds when the servo reaches the target angle.

uint8 index       # ID of the servo (between 0 and 2)
float32 angle     # absolute target angle in rad
---

---
float32 progress  # the relative progress towards goal from 0 to 1
