# Summary of vision detections

std_msgs/Header header                      # header with the time stamp of the update
robomaster_msgs/DetectedPerson[]  people    # A list of people detections
robomaster_msgs/DetectedRobot[]   robots    # A list of robots detections
robomaster_msgs/DetectedGesture[] gestures  # A list of gestures detections
robomaster_msgs/DetectedLine[]    lines     # A list of lines detections
robomaster_msgs/DetectedMarker[]  markers   # A list of markers detections
